export const FETCH_EXERCISES = 'FETCH_EXERCISES';
export const POST_EXERCISE = 'POST_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const FETCH_USERS = 'FETCH_USERS';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const GET_EXERCISE = 'GET_EXERCISE';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';